// <auto-generated />
using System;
using FastFoodManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace OOP_Cuoi_Ky.Migrations
{
    [DbContext(typeof(FastFoodContext))]
    [Migration("20241201210159_TenMigrationMoi")]
    partial class TenMigrationMoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastFoodManagement.Customer", b =>
                {
                    b.Property<int>("MAKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAKH"));

                    b.Property<decimal>("DiemTichLuy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAKH");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FastFoodManagement.Employee", b =>
                {
                    b.Property<int>("MANV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MANV"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANV");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FastFoodManagement.Invoice", b =>
                {
                    b.Property<int>("MAHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAHD"));

                    b.Property<string>("HinhThucTT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MAKH")
                        .HasColumnType("int");

                    b.Property<int>("MANV")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienNhan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianTT")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MAHD");

                    b.HasIndex("MAKH");

                    b.HasIndex("MANV");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FastFoodManagement.InvoiceDetail", b =>
                {
                    b.Property<int>("MAHD")
                        .HasColumnType("int");

                    b.Property<int>("MASP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MAHD", "MASP");

                    b.HasIndex("MASP");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("FastFoodManagement.Product", b =>
                {
                    b.Property<int>("MASP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MASP"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MASP");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("FastFoodManagement.Promotion", b =>
                {
                    b.Property<int>("MAKM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAKM"));

                    b.Property<bool>("DaDung")
                        .HasColumnType("bit");

                    b.Property<string>("DieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MAKH")
                        .HasColumnType("int");

                    b.Property<decimal>("MucGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianHL")
                        .HasColumnType("datetime2");

                    b.HasKey("MAKM");

                    b.HasIndex("MAKH");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("FastFoodManagement.Invoice", b =>
                {
                    b.HasOne("FastFoodManagement.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FastFoodManagement.Employee", "Employee")
                        .WithMany("Invoices")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("FastFoodManagement.InvoiceDetail", b =>
                {
                    b.HasOne("FastFoodManagement.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("MAHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodManagement.Product", "Product")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("MASP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastFoodManagement.Promotion", b =>
                {
                    b.HasOne("FastFoodManagement.Customer", "Customer")
                        .WithMany("Promotions")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FastFoodManagement.Customer", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("FastFoodManagement.Employee", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("FastFoodManagement.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("FastFoodManagement.Product", b =>
                {
                    b.Navigation("InvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
